name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
            echo "Hello Amol"
            echo "Hello Trupti"
            echo "Hello Shinde"
      - name: print goodbye
        run: echo "Done bye"
          
  
