name: Output Workflow
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print system information
        run: |
            echo "Operating System Information:"
            uname -a
            echo "Current Directory:"
            pwd
            echo "List of Files:"
            ls -la
      - name: Print environment variables
        run: printenv
      - name: Print GitHub context
        run: echo "${{ toJson(github) }}"